type User {
  id: ID!
  name: String!
  email: String!
  age: Int
  posts: [Post]
}

type Product {
  id: ID!
  title: String!
  price: Float!
  releaseYear: Int
  rating: Float
  inStock: Boolean!
}

type Post {
  id: ID!
  author: String!
  title: String!
  body: String!
  published: Boolean!
}

type Query {
  greeting(name: String): String!
  add(numbers: [Float!]!): Float!
  name: String!
  age: Int!
  employed: Boolean!
  gpa: Float
  user: User!
  product: Product!
  posts: [Post!]
  userPosts(author: String!): [Post!]
}
